name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Yin & Yang are you running?
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: How did you install Yin & Yang?
      options:
        - Git clone + running install script
        - AUR
        - Flatpak
    validations:
      required: true
  - type: dropdown
    id: desktop
    attributes:
      label: What desktop environments are you seeing the problem on?
      multiple: true
      options:
        - KDE
        - Gnome
        - Xfce
        - Mate
        - Cinnamon
        - other
  - type: dropdown
    id: plugins
    attributes:
      label: Which plugin causes the issue?
      options:
        - Atom
        - Brave
        - Colors
        - Custom Script
        - Firefox
        - Gedit
        - GTK
        - Konsole
        - Kvantum
        - Only Office
        - System
        - VSCode
        - Wallpaper
  - type: input
    id: plugin_version
    attributes:
      label: What software version do you use?
      description: For example, if you see a problem with the VSCode plugin, this would refer to the version of VSCode you have installed.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
